language: python
python:
  - 3.9

# Update pip to the latest version
before_install:
  - python --version
  - pip3 install -U pip

# install:
#   - pip3 install -r requirements.txt

script:
  - python -m unittest tests/quanthon_test.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main