language: python
python:
  - 3.11

# Update pip to the latest version
before_install:
  - python --version
  - pip3 install -U pip

install:
  - pip3 install -r requirements.txt

script:
  - python -m unittest tests/multiplication_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main